### ISSUE TITLE
Failed to run the server

### ISSUE THREAD

**Issue by sanyaade-iot** [highmobility/bluetooth-websocket-server#1]
Hello Everybody,

I went around to set up bluetooth-websocket-server locally and test it on my server. so far I am getting when I run the command: mix phoenix.server 
Please see below:

`Compiling 2 files (.ex)

== Compilation error in file lib/bluetooth_websocket_server/endpoint.ex ==
** (CompileError) lib/bluetooth_websocket_server/endpoint.ex:1: inlined function current_time/0 undefined
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
sanyaade@ns1:/var/www/html/site22/mercedeschallenge/socket-server$ 
`
I have looked into phoenix/endpoint/instrument but changes there have no effect. Please help

Hear from you soon!

God blesses!!!

Best regards,
Sanyaade

**Comment by slashmili** [comment]
@sanyaade-iot I'm working on upgrading the project to work on latest Elixir.

**Comment by slashmili** [comment]
@sanyaade-iot please fetch the new changes

```
cd project-dir
mkdir -p priv/keys/
openssl genrsa -out priv/keys/localhost.key 2048
openssl req -new -x509 -key priv/keys/localhost.key -out priv/keys/localhost.cert -days 3650 -subj /CN=localhost
mix deps.get
cd assets && npm install && cd ..
mix phx.server
```

**Comment by sanyaade-iot** [comment]
@slashmili  
Many thanks for the update. I will go with your new instruction today and feedback on my progress.
Once again, many thanks!

God blesses!!!

Best regards,
Sanyaade

**Comment by sanyaade-iot** [comment]
@slashmili:
Great this seems to be working very well. See my output below, I changed my port to 4060 since I already have another application using 4000 and port 80.

> 
sanyaade@ns1:/var/www/html/site22/mercedeschallenge/blesocketserver$ mix phx.server
[info] Running BluetoothWebsocketServerWeb.Endpoint with Cowboy using https://0.0.0.0:4060
12:25:28 - info: compiled 6 files into 2 files, copied 3 in 1.8 sec

and initial page at: https://educateiot.com:4060/ 
console output below: 
> sanyaade@ns1:/var/www/html/site22/mercedeschallenge/blesocketserver$ mix phx.server
[info] Running BluetoothWebsocketServerWeb.Endpoint with Cowboy using https://0.0.0.0:4060
12:25:28 - info: compiled 6 files into 2 files, copied 3 in 1.8 sec
[info] ['TLS', 32, 'server', 58, 32, 73, 110, 32, 115, 116, 97, 116, 101, 32, 'connection', 32, 'received CLIENT ALERT: Fatal - Unknown CA', 10]
[info] GET /
[debug] Processing with BluetoothWebsocketServerWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 40ms
[info] JOIN "bws:battery" to BluetoothWebsocketServerWeb.BatteryChannel
  Transport:  Phoenix.Transports.WebSocket (2.0.0)
  Serializer:  Phoenix.Transports.V2.WebSocketSerializer
  Parameters: %{}
[debug] BatteryChannel joined by socket: %Phoenix.Socket{assigns: %{}, channel: BluetoothWebsocketServerWeb.BatteryChannel, channel_pid: #PID<0.341.0>, endpoint: BluetoothWebsocketServerWeb.Endpoint, handler: BluetoothWebsocketServerWeb.UserSocket, id: nil, join_ref: "1", joined: false, private: %{log_handle_in: :debug, log_join: :info}, pubsub_server: BluetoothWebsocketServer.PubSub, ref: nil, serializer: Phoenix.Transports.V2.WebSocketSerializer, topic: "bws:battery", transport: Phoenix.Transports.WebSocket, transport_name: :websocket, transport_pid: #PID<0.336.0>, vsn: "2.0.0"}
[info] Replied bws:battery :ok

Next is to get a client to communicate eith the server, got some hardware to play with, and possible some mobile apps. I will feed you back on client progress soon!

Cheers!

God blesses!!!

Best regards,
Sanyaade
